### ISSUE TITLE
Add support to PhpStorm 2022.2

### ISSUE THREAD

**Issue by pniaps** [NiclasvanEyk/jetbrains-laravel-make-integration#51]
Hi.

The plugin has been "updated" to v2.3.5 when installed PhpStorm 2022.2.

I would help if i knew how to do it.

Thanks.

**Comment by NiclasvanEyk** [comment]
Thanks for reminding me!

I just published [v3.3.0](https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/releases/tag/v3.3.0), which will get approved by Jetbrains in the next few days. If you don't want to wait, you can [download the jar-file](https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/suites/7635234685/artifacts/317433214) and install it from disk.

The version always gets "updated" to 2.3.5. since this was the last version where I did not set an upper bound for the IDE version. Right now I am pinning it to the current version, otherwise I can not react to breaking changes in the API.
Still need to figure out how to best handle such pre-releases and publich a version for the next IDE version, once it hits EAP availability.
